### ISSUE TITLE
Unexpected receive action timeout while actually message was received

### ISSUE THREAD

**Issue by olha-bastieieva** [christophd/citrus#205]
At the certain stage in our test case we need to send request to the client, and since client has parallel threads for request processing and for the related to that request flow, I'm using parallel container.
Steps look like:
```
 http()
                .client(<client_name>)
                .post()
                .header("Content-Type", "text/xml")
                .fork(true)
                .payload (....);

        parallel().actions(
                sequential().actions(
                        http()
                                .client(<client_name>)
                                .response(OK)
                                .messageType("xml")
                ),
                sequential().actions(
//here we are receiving other requests from client and sending responses
)
```
With such test case structure test case **sometimes fails** (~2 out of 10 runs) due to "Action timeout while receiving synchronous reply message from http server", while in log I see that response was received and correlation id saved.

**Comment by olha-bastieieva** [comment]
Part of the log:
```14:42:42,026 DEBUG ns.SendMessageAction| Forking message sending action ...
14:42:42,027 INFO         citrus.Citrus| 
14:42:42,028 DEBUG        citrus.Citrus| TEST STEP 23/27 SUCCESS
14:42:42,028 INFO         citrus.Citrus| 
14:42:42,028 DEBUG        citrus.Citrus| TEST STEP 24/27: parallel
14:42:42,028 DEBUG        citrus.Citrus| TEST ACTION CONTAINER with 2 embedded actions
14:42:42,033 DEBUG nnel.ChannelConsumer| Receiving message from: EVR_services.inbound
14:42:42,033 DEBUG ngCorrelationManager| Get correlation key for 'citrus_message_correlator_Trigger_MSREF'
14:42:42,034 DEBUG   citrus.RetryLogger| Correlation key not available yet - retrying in 300ms
14:42:42,041 DEBUG ltCorrelationManager| Saving correlation key for 'citrus_message_correlator_Trigger_MSREF'
14:42:42,041 DEBUG  context.TestContext| Setting variable: citrus_message_correlator_Trigger_MSREF with value: 'citrus_message_id = '3ca5eafd-966b-49c4-9c21-2c5ec3a12ea8''
14:42:42,042 DEBUG    client.HttpClient| Sending HTTP message to: 'http://localhost:8081/ode/processes/MSREF'
14:42:42,042 DEBUG    client.HttpClient| Message to send:
<...forked request message here...>

14:42:42,043 DEBUG ingClientInterceptor| Sending Http request message
14:42:42,043 DEBUG   Logger.Message_OUT| POST http://localhost:8081/ode/processes/MSREF
Accept:text/plain, application/json, application/*+json, */*
Content-Type:text/xml
Content-Length:2463
Accept-Charset: <.....>

<...forked request mesage here...>

14:42:42,059 DEBUG ingClientInterceptor| Received Http response message
14:42:42,059 DEBUG    Logger.Message_IN| HTTP/1.1 200 OK
Server:Apache-Coyote/1.1
Set-Cookie:JSESSIONID=2EFD1060F8B676FCCE3B937583BB04F6; Path=/ode/; HttpOnly
Accept:text/xml, text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
SOAPAction:""
Content-Type:text/xml;charset=utf-8
Content-Length:963
Date:Tue, 14 Feb 2017 12:42:41 GMT

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><SOAP-ENV:Body><jmsIdResponse xmlns="http://www.revenue.ie/schemas/ccn-csi/schemas/send-message-response/v1" xmlns:ns10="http://www.revenue.ie/itp/om/messaging/output" xmlns:ns11="http://www.revenue.ie/schemas/common/revenue-types-v1" xmlns:ns2="http://www.revenue.ie/schemas/ros/form/integration/v1/ros-submission-schema-v1" xmlns:ns3="urn:ec.europa.eu:taxud:fiscalis:vatrefund:v1" xmlns:ns4="urn:ec.europa.eu:taxud:fiscalis:common:v1" xmlns:ns5="http://www.revenue.ie/schemas/evr/national-vat-app/v1" xmlns:ns6="http://www.revenue.ie/schemas/itp/banking/common/model/ItpBankingPaymentRequest" xmlns:ns7="http://www.revenue.ie/schemas/evr/services/evr-common-types/v1" xmlns:ns8="urn:ec.europa.eu:taxud:fiscalis:message:v1" xmlns:ns9="http://www.revenue.ie/schemas/ccn-csi/schemas/send-message-request/v1">Received</jmsIdResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
14:42:42,060 INFO     client.HttpClient| HTTP message was sent to endpoint: 'http://localhost:8081/ode/processes/MSREF'
14:42:42,061 DEBUG ltCorrelationManager| Saving correlated object for 'citrus_message_id = '3ca5eafd-966b-49c4-9c21-2c5ec3a12ea8''
14:42:42,071 DEBUG ngHandlerInterceptor| Received Http request:
HTTP/1.1 POST /integration/evr/service/validation
SOAPAction:""
Accept:text/xml, text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Cache-Control:no-cache
User-Agent:Java/1.7.0_45
Connection:keep-alive
Host:localhost:8082
Accept-Encoding:gzip
Pragma:no-cache
Content-Length:10035
Content-Type:text/xml; charset=UTF-8

<...request from the client at next parallel branch is here...>
14:42:42,073 DEBUG annelEndpointAdapter| Forwarding request to message channel ...
14:42:42,073 DEBUG t.TestContextFactory| Created new test context - using global variables: '{project.name=Citrus Integration Tests}'
14:42:42,073 DEBUG ltCorrelationManager| Saving correlation key for 'citrus_message_correlator_ChannelEndpointAdapter:producer'
14:42:42,073 DEBUG  context.TestContext| Setting variable: citrus_message_correlator_ChannelEndpointAdapter:producer with value: 'citrus_message_id = '31547810-131c-4555-b530-a2121a4dbaee''
14:42:42,074 DEBUG .ChannelSyncProducer| Sending message to channel: 'EVR_services.inbound'`

**Comment by olha-bastieieva** [comment]
and at the log later we have records like:
```
14:43:41,402 DEBUG ltCorrelationManager| Finding correlated object for 'citrus_message_id = '3ca5eafd-966b-49c4-9c21-2c5ec3a12ea8''
14:43:41,402 DEBUG   citrus.RetryLogger| Reply message did not arrive yet - retrying in 500ms
14:43:41,901 DEBUG ltCorrelationManager| Finding correlated object for 'citrus_message_id = '3ca5eafd-966b-49c4-9c21-2c5ec3a12ea8''
14:43:41,901 DEBUG   citrus.RetryLogger| Reply message did not arrive yet - retrying in 500ms
14:43:42,400 DEBUG ltCorrelationManager| Finding correlated object for 'citrus_message_id = '3ca5eafd-966b-49c4-9c21-2c5ec3a12ea8''
14:43:42,401 ERROR   container.Parallel| Parallel test action raised error
com.consol.citrus.exceptions.ActionTimeoutException: Action timeout while receiving synchronous reply message from http server
	at com.consol.citrus.http.client.HttpClient.receive(HttpClient.java:146)
	at com.consol.citrus.http.client.HttpClient.receive(HttpClient.java:137)
	at com.consol.citrus.actions.ReceiveMessageAction.receive(ReceiveMessageAction.java:146)
	at com.consol.citrus.actions.ReceiveMessageAction.doExecute(ReceiveMessageAction.java:125)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.dsl.actions.DelegatingTestAction.doExecute(DelegatingTestAction.java:54)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.container.Parallel$ActionRunner.run(Parallel.java:107)
	at java.lang.Thread.run(Thread.java:745)
14:43:42,408 INFO         citrus.Citrus| 
14:43:42,408 ERROR        citrus.Citrus| TEST FAILED MSEST_VAT_Refund_application_TC01 <ie.revenue.integration> Nested exception is: 
com.consol.citrus.exceptions.ActionTimeoutException: Action timeout while receiving synchronous reply message from http server```

**Comment by christophd** [comment]
You are doing a lot of parallelism in your test. Forking the first http send operation in combination with parallel container can lead to racing conditions. I suggest to remove the parallel container in your test as it is not required here. 

You should put the http().client().receive().response(OK) to the very end of your test. You can do other actions in between http().client() request and response without having to use parallel containers everywhere.

**Comment by olha-bastieieva** [comment]
Many thanks, that solved the issue.
