### ISSUE TITLE
Support Parameterized JUnit4 runner in combination with Junit4CitrusTestDesigner

### ISSUE THREAD

**Issue by rhuss** [christophd/citrus#230]
When using parameterised unit tests as described in https://github.com/junit-team/junit4/wiki/parameterized-tests then Citrus throws an NPE when using the `TestDesigner`:

```
Caused by: java.lang.NullPointerException
	at com.consol.citrus.dsl.junit.JUnit4CitrusTestDesigner.http(JUnit4CitrusTestDesigner.java:432)
	at com.consol.citrus.dsl.junit.JUnit4CitrusTestDesigner$http.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:158)
	at org.jolokia.it.BaseJolokiaTest.jolokiaClient(BaseJolokiaTest.groovy:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:158)
	at org.jolokia.it.read.ReadGetIT.prepareReadThen(ReadGetIT.groovy:219)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at org.jolokia.it.read.ReadGetIT.mxBeanWithComplexKey(ReadGetIT.groovy:204)
	... 33 more
``

I suspect that `Junit4CitrusTest.run()` is never called when an extra JunitRunner is installed with `RunWith()`. But that's only a gut feeling.

**Comment by christophd** [comment]
Paremterized tests for JUnit are indeed not supported yet in Citrus. Will try to add this with next release. Maybe switching to TestNG data provider is some solution for you as this is already supported in Citrus.

**Comment by christophd** [comment]
JUnit4 does not support multiple `@RunWith` annotations so we can not combine `Parameterized` runner with Citrus JUnit4CitrusTestDesigner runner.

We have to wait for JUnit5 which is scheduled for July'17

**Comment by christophd** [comment]
Please refer to https://github.com/christophd/citrus/issues/143 that will add JUnit5 support in Citrus. This will also cover parameterized tests.
