### ISSUE TITLE
propagateError for SOAP send() action

### ISSUE THREAD

**Issue by johnsliao** [christophd/citrus#236]
Is there a propagateError for SOAP send() action? In the Citrus documentation, I understand there is one for the retrieve action():

> We have configured a fault strategy propagateError so the message sender will not raise client exceptions but inform the receive action with SOAP fault message contents. By default the fault strategy raises client exceptions (fault-strategy= throwsException).

```
<citrus-ws:client id="soapClient"
                               request-url="http://localhost:8090/test"
                               fault-strategy="propagateError"/>
```

I am writing a test that is returning a Bad Request [400], which actually expected behavior for a negative test case. 

Here is the stack track:

```
org.springframework.ws.client.WebServiceTransportException: Bad Request [400]
	at org.springframework.ws.client.core.WebServiceTemplate.handleError(WebServiceTemplate.java:699)
	at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:609)
	at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:555)
	at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:531)
	at com.consol.citrus.ws.client.WebServiceClient.send(WebServiceClient.java:126)
...
```

Thanks for the help here.

**Comment by christophd** [comment]
There is a difference between SOAP fault responses and Http error responses. The Http 400 error is always raising exceptions within the send operation. This kind of exception is never propagated to the receive. The fault strategy only applies to SOAP fault responses. These faults are Http 200 although marking a fault from semantical point of view.
