### ISSUE TITLE
java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.

### ISSUE THREAD

**Issue by scannerscan** [christophd/citrus#237]
I am getting the exception below when try to execute the same test multiple times using TestNG:

     @Test(threadPoolSize = 2, invocationCount = 2)
    @Parameters( { "testRunner" })
    @CitrusTest(name = "2 parallel posting.")
    public void testBug1(
                 @Optional
                 @CitrusResource TestRunner testRunner) {

testRunner.http(request -> request
            .client("httpClient").send()
            .post()
            .path("/todoThings/")
            .contentType(ContentType.APPLICATION_JSON.toString())
            .messageType(MessageType.JSON)
            .payload(new TestModel()
                .defaultData(uuid)
                .entry(new MyEntryModel()
                    .request(uuid)).build()));

}

one thread works with no issues.

com.consol.citrus.exceptions.TestCaseFailedException: Test case failed

	at com.consol.citrus.TestCase.executeAction(TestCase.java:236)
	at com.consol.citrus.dsl.runner.DefaultTestRunner.run(DefaultTestRunner.java:198)
	at com.consol.citrus.dsl.runner.DefaultTestRunner.http(DefaultTestRunner.java:534)
	at bugs.ParallelExecutionTestNGCase.testBug1(ParallelExecutionTestNGCase.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.invokeTestMethod(TestNGCitrusTest.java:142)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.run(TestNGCitrusTest.java:111)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.run(TestNGCitrusTest.java:57)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:221)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:657)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.impl.conn.BasicClientConnectionManager.getConnection(BasicClientConnectionManager.java:163)
	at org.apache.http.impl.conn.BasicClientConnectionManager$1.getConnection(BasicClientConnectionManager.java:145)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:422)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:89)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:531)
	at com.consol.citrus.http.client.HttpClient.send(HttpClient.java:117)
	at com.consol.citrus.actions.SendMessageAction.doExecute(SendMessageAction.java:118)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.dsl.actions.DelegatingTestAction.doExecute(DelegatingTestAction.java:54)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.TestCase.executeAction(TestCase.java:229)
	... 22 more

**Comment by scannerscan** [comment]
citrusframework 2.7.1

**Comment by scannerscan** [comment]
It is fixable by modifying http client config over spring config.
