### ISSUE TITLE
Unable to create endpoint for static endpoint adapter error

### ISSUE THREAD

**Issue by ploef** [christophd/citrus#240]
Hi,

I'm evaluating Citrus as a framework for integration testing at the moment bum I'm stumbling into a problem.
I'm starting a http server using the following settings:
```
 <citrus-http:server id="httpServer"
                      port="8082"
                      auto-start="true"
                      resource-base="src/it/resources"
                      endpoint-adapter="emptyResponseEndpointAdapter" timeout="20000" />
   <citrus:empty-response-adapter id="emptyResponseEndpointAdapter"/>
```

In Java code I use:
```
 @Autowired
    private HttpServer httpServer;

    @Test
    @CitrusTest
    public void testAddTodoEntry() {

        http().server(httpServer) 
          .receive()
          .post("/receive")
          .schemaValidation(false);
    }
```

When I'm starting the test I get the following error:

```
com.consol.citrus.exceptions.CitrusRuntimeException: Unable to create endpoint for static endpoint adapter type 'class com.consol.citrus.endpoint.adapter.EmptyResponseEndpointAdapter'
	at com.consol.citrus.endpoint.adapter.StaticEndpointAdapter.getEndpoint(StaticEndpointAdapter.java:35)
	at com.consol.citrus.server.AbstractServer.createConsumer(AbstractServer.java:209)
	at com.consol.citrus.actions.ReceiveMessageAction.receive(ReceiveMessageAction.java:150)
	at com.consol.citrus.actions.ReceiveMessageAction.doExecute(ReceiveMessageAction.java:129)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.dsl.actions.DelegatingTestAction.doExecute(DelegatingTestAction.java:54)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.TestCase.executeAction(TestCase.java:229)
	at com.consol.citrus.TestCase.doExecute(TestCase.java:145)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.Citrus.run(Citrus.java:256)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.invokeTestMethod(TestNGCitrusTest.java:136)
	at com.consol.citrus.dsl.testng.TestNGCitrusTestDesigner.invokeTestMethod(TestNGCitrusTestDesigner.java:73)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.run(TestNGCitrusTest.java:111)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.run(TestNGCitrusTest.java:57)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:641)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:134)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:118)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

Does anybody have any idea what I'm doing wrong here?

Best regards,
Peter

**Comment by christophd** [comment]
When adding the endpoint adapter to the server component ALL requests will automatically get an empty response. The request is therefore not propagated to the test receive operation. You can not mix the endpoint adapters with receive operations in your test. Remove the endpoint adapter, receive and validate the request in your test and respond with empty message in your test.

**Comment by ploef** [comment]
Hi Christoph,
Thank you for the quick response! It seems to work now for receiving one message.
Unfortunately I'm looking for a way to test the situation where I'm expecting to receive multiple messages and to validate them all. Some kind of aggregation before continuing the test.
Would that be possible also?

Regards,
Peter

**Comment by christophd** [comment]
You can put the receive-send operations into an iterate container (http://www.citrusframework.org/reference/html/containers-iterate.html). But you would still have to know how many messages should be handled this way.

**Comment by ploef** [comment]
The last few hours Citrus keeps amazing me. ;-) I will check out this option, thank you.

**Comment by ploef** [comment]
Hi,

It seems that the test I have in mind is going to be a bit to complicated unfortunately. I looked in to the possibility of using the iterate container but get stuck on the implementation.

What I'm trying to do is creating an integration test for a Enterprise Service Bus (ESB). This brings the following complications:

* one message going to the ESB results in 1 or more messages coming out. I do know how many messages I expect (is to be tested also).
* Every message coming from the ESB has been send to a different endpoint. So I have to be sure that there is a receive operation for everyone of them.
*Every message coming from the ESB should get a correct response from the test. Otherwise the error handling is started in the ESB resulting in retries of placing messages in dead letter queues.

It looks like I have it working for receiving one message send to a specific endpoint but this means the others produce errors in the ESB because there is no endpoint listening for them:

```
 soap().server(httpServer)
                .receive()
                .selector("citrus_http_request_uri='/uas'")
                .payload(new ClassPathResource("templates/esb-to-uas.xml"));

        soap().server(httpServer)
                .send()
                .status(HttpStatus.ACCEPTED)
                .payload("<?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"><soapenv:Body/></soapenv:Envelope>");
```
If I understand correctly I could place these two operation inside a iterate container but I'm struggling with the dynamic endpoints (selectors), validation payload and response payload.

Do you have experience with testing a situation like this?

Regards,
Peter

**Comment by christophd** [comment]
All incoming messages on that same Citrus http soap server port get forwarded to the test case for validation. Messages on different request paths, operations and so on are all forwarded to the same inbound queue for the test. 

So you have to pick the message based on some selector. You can use header values or XPath expressions for selecting the messages from inbound. Otherwise without a selector you would simply get the messages in that same order as they have arrived on the http soap server. Following from that you can use multiple `soap().server(xxx).receive()` actions in a test. With proper selectors on these receive actions you pick the messages as you expect them in your test. So you do not necessarily need an iterating container. Instead you just use multiple receive and send operations in that test.

Hope that helps!
