### ISSUE TITLE
How can i run citrus tests on command line without maven/gradle?

### ISSUE THREAD

**Issue by tbahadur** [christophd/citrus#325]
I am looking to use citrus for end user testing automation. The idea is to package all tests together as a separate application and have them executed on a prod parallel environment. No maven etc. Can i run these tests just like a regular java application. Also can this be done without junit/testNG?

**Comment by christophd** [comment]
You can use a custom main class that executes the tests in your project:

    public class App {
        public static void main(String[] args) {
            String suiteName = "mySuite";
    
            Citrus citrus = Citrus.newInstance();
            try {
                citrus.beforeSuite(suiteName);
    
                citrus.run(new XmlTestLoader(App.class, "SampleXmlTest", "com.consol.citrus.tests", citrus.getApplicationContext()).load());
    
                citrus.run(new SampleJavaDslTest().getTestCase());
    
                citrus.afterSuite(suiteName);
            } finally {
                ((ConfigurableApplicationContext) citrus.getApplicationContext()).close();
            }
        }
    
        private static class SampleJavaDslTest extends DefaultTestDesigner {
            public SampleJavaDslTest() {
                super();
                echo("Hello from Java DSL!");
            }
        }
    }

The main class above creates a new Citrus instance and runs the XML test `SampleXmlTest`. This should be a file located in `com/consol/citrus/tests/SampleXmlTest.xml`. Also the Java DSL test designer is run directly as instance. The before/after suite makes sure that the Citrus reports are printed as usual.

**Comment by tbahadur** [comment]
Thanks for your quick response. Will test this out.

**Comment by tbahadur** [comment]
This works great. It produces the HTML test results output except if any test case is failing. I added following to my test case - 
`<fail message="Test will fail with custom message"/>`

If a test case fails, i don't see any test result output. Is it possible to still produce an output report showing which test cases failed. I can see below trail..

` INFO [Thread-0] (XmlBeanDefinitionReader.java:316) - Loading XML bean definitions from class path resource [com/consol/citrus/spring/annotation-config-ctx.xml]
 INFO [Thread-0] (EchoAction.java:51) - Hello Test Framework
 INFO [Thread-0] (LoggingReporter.java:259) -
ERROR [Thread-0] (LoggingReporter.java:89) - TEST FAILED MyFirstTest <com.nomura.gm.eps.trading.tests> Nested exception is:
com.consol.citrus.exceptions.CitrusRuntimeException: Test will fail with custom message
        at com.consol.citrus.actions.FailAction.doExecute(FailAction.java:40)
        at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
        at com.consol.citrus.TestCase.executeAction(TestCase.java:229)
        at com.consol.citrus.TestCase.doExecute(TestCase.java:145)
        at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
        at com.consol.citrus.Citrus.run(Citrus.java:281)
        at com.consol.citrus.Citrus.run(Citrus.java:272)
        at com.nomura.gm.eps.trading.tests.App.init(App.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1835)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1778)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$5/746097645.getObject(Unknown Source)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:758)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at com.nomura.gm.eps.trading.app.SessionContext.initContext(SessionContext.java:66)
        at com.nomura.gm.eps.trading.app.SessionContext.<init>(SessionContext.java:26)
        at com.nomura.gm.eps.trading.app.Main.run(Main.java:42)
        at java.lang.Thread.run(Thread.java:745)
 INFO [Thread-0] (LoggingReporter.java:252) - ------------------------------------------------------------------------
 INFO [Thread-0] (LoggingReporter.java:259) -
 INFO [Thread-0] (AbstractApplicationContext.java:989) - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@34e5daa0: startup date [Fri Jan 12 08:56:14 EST 2018]; root of context hierarchy
 WARN [Thread-0] (Main.java:52) -  No LifecycleManager defined!! Some lifecycle dependencies might not initialize
`

**Comment by tbahadur** [comment]
Never mind, please ignore my previous comment. I should have read your answer more thoroughly

> The before/after suite makes sure that the Citrus reports are printed as usual.

So just need to ensure after suite runs.

**Comment by tbahadur** [comment]
How can I create my own endpoint - for example for TibcoRV or custom TCP? Thanks.

**Comment by christophd** [comment]
There is a citrus-tibco module that provides full integration with TIBCO Rendezvous. Due to licensing this is not available on Maven central. Please send me a direct message so we can discuss how to provide this module to you. Please mail to citrus-dev-l@consol.de and refer to this conversation. Thx!

Closing this issue as it is a different story
