### ISSUE TITLE
TestNG 6.13.1 leads to out of memory in surefire fork

### ISSUE THREAD

**Issue by FMAOuroboros** [christophd/citrus#337]
Hi!

During my development, I found out that I was unable to build the citrus-core module after the update of TestNG to 6.13.1, due to forever running test ending up in a `java.lang.OutOfMemoryError: Java heap space` exception. This occurred during surefire forked test.

```xml
<plugin>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>2.20.1</version>
  <configuration>
    <systemProperties>
      <property>
        <name>javax.xml.parsers.SAXParserFactory</name>
        <value>org.apache.xerces.jaxp.SAXParserFactoryImpl</value>
      </property>
      <property>
        <name>user.language</name>
        <value>en</value>
      </property>
    </systemProperties>
    <forkMode>once</forkMode>
    <failIfNoTests>false</failIfNoTests>
    <skipTests>${skip.unit.tests}</skipTests>
    <excludes>
      <exclude>**/IT*.java</exclude>
      <exclude>**/*IT.java</exclude>
    </excludes>
    <workingDirectory>${project.build.directory}</workingDirectory>
  </configuration>
</plugin>
```

One should try to find the root cause, test whether newer/older TestNG versions have the same problem and report an issue to the TestNG devs as far as it is a TestNG related root cause.

**Comment by FMAOuroboros** [comment]
Hi!

I investigated the issue with the newest TestNG version 6.14.2 and unfortunately the problem still exists.

Here is the detailed stack trace for further investigation.
```
[ERROR] There was an error in the forked process
[ERROR] Java heap space
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Java heap space
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:673)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by tushar025** [comment]
Hi FMAOuroboros, I am facing exactly same exception for same testng version. May I know if you found any solution?
Is it related to Surefire plugin? https://github.com/junit-team/junit5/issues/855
I am using surefire 2.20, which version are you using?

**Comment by FMAOuroboros** [comment]
Hey @tushar025!

Unfortunately I haven't had the chance to investigate any further. We're using surefire 2.20.1.

**Comment by FMAOuroboros** [comment]
I tried surefire 2.21.0 and 2.19.1 with the same result. In addition, @christophd told me, that he has no issues on his MAC. 
Nevertheless our build server also runs into a slightly different issue.

```
[ERROR] There was an error in the forked process
[ERROR] GC overhead limit exceeded
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] GC overhead limit exceeded
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:673)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by FMAOuroboros** [comment]
Finally got something that worked. I exchanged the `<forkMode>once</forkMode>` with `<forkMode>always</forkMode>`. This does not solve the root problem but it's a workaround.

Concerning the solution:
If I reuse the fork, as `<forkMode>once</forkMode>` would do, the heap grows until the jvm crashes. If I throw the fork away everytime, the heap cannot grow up that much, because the fork is destroyed. 93c9bd6 is the commit, where the change was made. 
From my perspective, we've three candidates that could cause the problem. The first one is TestNG, because the issue occurred first after a TestNG Version upgrade, surefire that may have a memory management issue and citrus which may have a problem when shutting down the context after the tests. I'll have a look at the TestNG integration of Citrus to ensure that this is not the case.

Nevertheless, finally this issue is done! =)

BR,
Sven

**Comment by FMAOuroboros** [comment]
The transition to `<forkMode>always</forkMode>` leads to a dramatically increased build times on machines with enough ram.

Therefore we removed `<forkMode>always</forkMode>` and replaced it with
```xml
 <forkCount>1</forkCount>
 <reuseForks>true</reuseForks>
```

If you have not enough ram to build citrus, you have to use `mvn clean install -DreuseForks=false` and get one or two cups of coffee. ;-)

BR,
Sven

**Comment by tushar025** [comment]
Hi @svettwer 
Thanks for sharing the workaround, it's working for me as well. Except the fact that my console output size grows tremendously (in GB) but I can live with that, you've been a great help to me. Thanks again!

**Comment by svettwer** [comment]
Hi @tushar025! 
Glad to hear that! I've also created a TestNG issue. https://github.com/cbeust/testng/issues/1788
The problem is known, fixed and will be part of the next release, which is unfortunately currently not scheduled.
Nevertheless, this might be interesting for you as well!
