### ISSUE TITLE
citrus-jms:sync-endpoint cannot receive the reply message on reply destination

### ISSUE THREAD

**Issue by zzhengesi** [christophd/citrus#349]
I ensure that both the request and reply destinations work on the MQ server.
I have tried many times with this citrus endpoint configuration 
but always get this timeout error in receiving the reply on the reply destination.
<citrus-jms:sync-endpoint id="faxGatewayClient"
                    destination-name="TEST.NRX.RESPONSE_1.0"
                    reply-destination-name="ECC.REQUEST.DWS.INT_1.0"
                    connection-factory="connectionFactory"
                    timeout="30000" />

How to fix this error?

------------------------- console output ------------------------------------
[INFO ] 2018-03-15 16:11:27,790 [main] JmsSyncProducer - Message was sent to JMS destination: 'TEST.NRX.RESPONSE_1.0'
[DEBUG] 2018-03-15 16:11:27,791 [main] JmsSyncProducer - Receiving reply message on destination: '{CCSID=1208, brokerCCDurSubQueue=SYSTEM.JMS.D.CC.SUBSCRIBER.QUEUE, JMS_IBM_Unmappable_Action=REPORT, failIfQuiesce=1, destDescription=null, readAheadClosePolicy=2, JMS_IBM_Unmappable_Replacement=63, mdWriteEnabled=false, XMSC_WMQ_QUEUE_MANAGER=, timeToLive=-2, putAsyncAllowed=-1, deliveryMode=-2, readAheadAllowed=-1, XMSC_DESTINATION_NAME=ECC.REQUEST.DWS.INT_1.0, wildcardFormat=0, mdReadEnabled=false, messageBody=2, XMSC_WMQ_BROKER_PUBQ=, XMSC_ADMIN_OBJECT_TYPE=33, priority=-2, encoding=273, brokerVersion=0, version=7, brokerDurSubQueue=SYSTEM.JMS.D.SUBSCRIBER.QUEUE, XMSC_CONNECTION_TYPE_NAME=com.ibm.msg.client.wmq, XMSC_WMQ_REPLYTO_STYLE=0, targetClient=0, mdMessageContext=0, XMSC_WMQ_BROKER_PUBQ_QMGR=, XMSC_CONNECTION_TYPE=1}'
[DEBUG] 2018-03-15 16:11:57,914 [main] JmsSyncProducer - Delete temporary destination: '{CCSID=1208, brokerCCDurSubQueue=SYSTEM.JMS.D.CC.SUBSCRIBER.QUEUE, JMS_IBM_Unmappable_Action=REPORT, failIfQuiesce=1, destDescription=null, readAheadClosePolicy=2, JMS_IBM_Unmappable_Replacement=63, mdWriteEnabled=false, XMSC_WMQ_QUEUE_MANAGER=, timeToLive=-2, putAsyncAllowed=-1, deliveryMode=-2, readAheadAllowed=-1, XMSC_DESTINATION_NAME=ECC.REQUEST.DWS.INT_1.0, wildcardFormat=0, mdReadEnabled=false, messageBody=2, XMSC_WMQ_BROKER_PUBQ=, XMSC_ADMIN_OBJECT_TYPE=33, priority=-2, encoding=273, brokerVersion=0, version=7, brokerDurSubQueue=SYSTEM.JMS.D.SUBSCRIBER.QUEUE, XMSC_CONNECTION_TYPE_NAME=com.ibm.msg.client.wmq, XMSC_WMQ_REPLYTO_STYLE=0, targetClient=0, mdMessageContext=0, XMSC_WMQ_BROKER_PUBQ_QMGR=, XMSC_CONNECTION_TYPE=1}'
[INFO ] 2018-03-15 16:11:57,916 [main] Citrus - 
[ERROR] 2018-03-15 16:11:57,916 [main] Citrus - TEST FAILED submitpaymenttransaction-steps-feature;get-response-for-a-valid-request-payload <com.consol.citrus.dsl.design> Nested exception is: 
com.consol.citrus.exceptions.ActionTimeoutException: Reply timed out after 30000ms. Did not receive reply message on reply destination
	at com.consol.citrus.jms.endpoint.JmsSyncProducer.send(JmsSyncProducer.java:116) ~[citrus-jms-2.7.1.jar:?]
	at com.consol.citrus.actions.SendMessageAction.doExecute(SendMessageAction.java:118) ~[citrus-core-2.6.2.jar:?]
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42) ~[citrus-core-2.6.2.jar:?]
	at com.consol.citrus.dsl.actions.DelegatingTestAction.doExecute(DelegatingTestAction.java:54) ~[citrus-java-dsl-2.6.2.jar:?]
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42) ~[citrus-core-2.6.2.jar:?]
	at com.consol.citrus.TestCase.executeAction(TestCase.java:226) [citrus-core-2.6.2.jar:?]
	at com.consol.citrus.TestCase.doExecute(TestCase.java:142) [citrus-core-2.6.2.jar:?]
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42) [citrus-core-2.6.2.jar:?]
	at com.consol.citrus.Citrus.run(Citrus.java:255) [citrus-core-2.6.2.jar:?]
	at com.consol.citrus.Citrus.run(Citrus.java:246) [citrus-core-2.6.2.jar:?]
	at com.consol.citrus.cucumber.CitrusLifecycleHooks.after(CitrusLifecycleHooks.java:61) [citrus-cucumber-2.6.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at cucumber.runtime.Utils$1.call(Utils.java:40) [cucumber-core-1.2.5.jar:?]
	at cucumber.runtime.Timeout.timeout(Timeout.java:16) [cucumber-core-1.2.5.jar:?]
	at cucumber.runtime.Utils.invoke(Utils.java:34) [cucumber-core-1.2.5.jar:?]
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60) [cucumber-java-1.2.5.jar:?]
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224) [cucumber-core-1.2.5.jar:?]
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212) [cucumber-core-1.2.5.jar:?]
	at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206) [cucumber-core-1.2.5.jar:?]
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46) [cucumber-core-1.2.5.jar:?]
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102) [cucumber-junit-1.2.5.jar:?]
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63) [cucumber-junit-1.2.5.jar:?]
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18) [cucumber-junit-1.2.5.jar:?]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70) [cucumber-junit-1.2.5.jar:?]
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95) [cucumber-junit-1.2.5.jar:?]
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38) [cucumber-junit-1.2.5.jar:?]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100) [cucumber-junit-1.2.5.jar:?]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367) [surefire-junit4-2.19.1.jar:2.19.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274) [surefire-junit4-2.19.1.jar:2.19.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238) [surefire-junit4-2.19.1.jar:2.19.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161) [surefire-junit4-2.19.1.jar:2.19.1]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290) [surefire-booter-2.19.1.jar:2.19.1]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242) [surefire-booter-2.19.1.jar:2.19.1]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121) [surefire-booter-2.19.1.jar:2.19.1]
[INFO ] 2018-03-15 16:11:57,927 [main] Citrus - ------------------------------------------------------------------------

**Comment by FMAOuroboros** [comment]
Hi!

In general, this timeout occurs, when citrus waits for a synchronous response on the specified topic but doesn't receive one. This could f.e. happen, if the JMS listener is configured for asynchronous communication.

Which Citrus version do you currently use?
I assume that you're using IBM MQ?

Btw:
Have you seen the [jms-synchronous-endpoints](http://www.citrusframework.org/reference/html/index.html#jms-synchronous-endpoints) section in the user guide?
I've also added synchronous jms examples to [citrus-samples (Java DSL)](https://github.com/christophd/citrus-samples) and [citrus-samples-xml (XML DSL)](https://github.com/christophd/citrus-samples-xml) for you

BR,
Sven

**Comment by zzhengesi** [comment]
Sven,
I find that Citrus does not work at all with JMS sync-endpoints for IBM MQ queues.

Sincerely,
Zhen Zheng

**Comment by FMAOuroboros** [comment]
Hi @zzhengesi.
Thanks for your response. I'm sorry to hear that! =/
Unfortunately we've no opportunity to test it on our side, because we've no IBM MQ available. As soon as we get the chance to work with IBM MQ, we'll investigate that problem.

BR,
Sven
