### ISSUE TITLE
Autowired does not work outside of Cucumber StepDefinitionsClass

### ISSUE THREAD

**Issue by pmurali1** [christophd/citrus#361]
Hello,

I am new to citrus, cucumber and spring. I am trying to build a test framework for our product using Cucumber and Citrus. So far, I have been liking it. But, currently i am stuck with an issue explained below. I need to demonstrate this to my management next week. Any help would be appreciated. 

I have a serviceregistry that maintains the list of services. Currently My stepdefinitions class looks as below :
 
    @Autowired
    @Qualifier("workServiceEndpoint")
    private HttpClient workServiceEndpoint;

    @When(API)
    public void invokeAPI() {
        manager = ServiceRegistryFactory.getHttpServiceRegistryInstance();
        service = manager.getService("work-service");
        api = service.getAPI("health-check");
        api.invoke(designer.http(), workServiceEndpoint, null);
    }

This works perfectly.. But, I do not want to pass the APIEndpoint as a parameter from the StepDefinition class. Each service can have a different type of endpoint and hence the Service class needs to inject the endpoint. However, when I do that , my test fails. 

My step definition will look as below : 

    @When(API)
    public void invokeAPI() {
        manager = ServiceRegistryFactory.getHttpServiceRegistryInstance();
        service = manager.getService("work-service");
        api = service.getAPI("health-check");
        api.invoke(designer.http(), service.getClient(), null);
    }

And in my Workservice Class, I want to do the auto-wiring of the endpoint . 

    public class Workservice {
        @Autowired
        @Qualifier("workServiceEndpoint")
        @CitrusEndpoint
        private HttpClient httpClient;

        // TODO: This will be loaded by config manager.For now, it is hardcoded.
        public Workservice() {
            apis.put("health-check", new GetAPI("health-check", HttpMethod.GET, webappContext + "/health"));
        }
    }

But the test fails with below exception - 

    2018-04-12 14:47:17.484 [main] INFO  com.consol.citrus.report.LoggingReporter - 
    2018-04-12 14:47:17.484 [main] ERROR com.consol.citrus.report.LoggingReporter - TEST FAILED src/test/resources/features/workservice/demo1.feature:21 <com.consol.citrus.dsl.design> Nested exception is: 
    com.consol.citrus.exceptions.CitrusRuntimeException: Neither endpoint nor endpoint uri is set properly!
	at com.consol.citrus.actions.SendMessageAction.getOrCreateEndpoint(SendMessageAction.java:176) ~[citrus-core-2.7.4.jar:?]
	at com.consol.citrus.actions.SendMessageAction.isDisabled(SendMessageAction.java:137) ~[citrus-core-2.7.4.jar:?]
	at com.consol.citrus.dsl.actions.DelegatingTestAction.isDisabled(DelegatingTestAction.java:60) ~[citrus-java-dsl-2.7.4.jar:?]
	at com.consol.citrus.TestCase.executeAction(TestCase.java:230) [citrus-core-2.7.4.jar:?]
	at com.consol.citrus.TestCase.doExecute(TestCase.java:153) [citrus-core-2.7.4.jar:?]
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:46) [citrus-core-2.7.4.jar:?]
 
How can I autowire the httpClient outside of my StepDefinitions class?

**Comment by FMAOuroboros** [comment]
Hey @pmurali1,

have you been able to solve the issue? 

BR, 
Sven

**Comment by FMAOuroboros** [comment]
Hi!
I assume that the issue has been solved.
If you've any questions, please don't hesitate to open a new issue!

BR,
Sven
