### ISSUE TITLE
Citrus setup using Ant

### ISSUE THREAD

**Issue by kaushalkishore12** [christophd/citrus#38]
I am new to citrus framework and trying to have a basic setup. I followed the steps mentioned in tutorial http://www.citrusframework.org/tutorials-ant.html
I tried running citrus with ant but everytime i am getting below error
c:\...\build.xml:47: java.lang.NoSuchMethodException: com.consol.citrus.Citrus.main([Ljava.lang.String;)
        at java.lang.Class.getMethod(Class.java:1670)
        at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:142)
        at org.apache.tools.ant.taskdefs.Java.run(Java.java:771)
        at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:221)
        at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
        at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
        at com.consol.citrus.ant.CitrusAntTask.execute(CitrusAntTask.java:79)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

List of jars included in my lib folder
activation-1.1.1.jar
antlr-2.7.7.jar
aopalliance-1.0.jar
asm-4.0.jar
asm-analysis-4.0.jar
asm-commons-4.0.jar
asm-tree-4.0.jar
asm-util-4.0.jar
bsh-2.0b4.jar
citrus-ant-tasks-2.1.jar
citrus-core-2.1.jar
citrus-http-2.1.jar
citrus-java-dsl-2.1.jar
citrus-jms-2.1.jar
citrus-model-core-2.1.jar
citrus-model-http-2.1.jar
citrus-model-jms-2.1.jar
citrus-model-ws-2.1.jar
citrus-ws-2.1.jar
com.springsource.javax.jms-1.1.0.jar
commons-cli-1.2.jar
commons-codec-1.9.jar
commons-httpclient-3.0.1.jar
commons-io-2.4.jar
commons-lang-2.6.jar
commons-logging-1.1.3.jar
commons-logging-api-1.1.jar
FastInfoset-1.2.12.jar
groovy-2.1.0.jar
groovy-json-2.1.0.jar
groovy-jsr223-2.1.0.jar
groovy-xml-2.1.0.jar
hamcrest-core-1.3.jar
httpclient-4.3.5.jar
httpcore-4.3.2.jar
istack-commons-runtime-2.16.jar
javax.servlet-3.0.0.v201112011016.jar
javax.xml.soap-api-1.3.5.jar
jaxb-api-2.2.7.jar
jaxb-core-2.2.7.jar
jaxb-impl-2.2.7.jar
jcl-over-slf4j-1.7.7.jar
jcommander-1.27.jar
jdom-1.0.jar
jetty-continuation-8.1.16.v20140903.jar
jetty-http-8.1.16.v20140903.jar
jetty-io-8.1.16.v20140903.jar
jetty-security-8.1.16.v20140903.jar
jetty-server-8.1.16.v20140903.jar
jetty-servlet-8.1.16.v20140903.jar
jetty-util-8.1.16.v20140903.jar
json-simple-1.1.1.jar
jsr173_api-1.0.jar
jtidy-r938.jar
junit-4.11.jar
log4j-1.2.17.jar
mimepull-1.9.jar
rome-1.0.0.jar
rome-fetcher-1.0.0.jar
saaj-impl-1.3.23.jar
serializer-2.7.2.jar
slf4j-api-1.7.7.jar
slf4j-log4j12-1.7.2.jar
snakeyaml-1.6.jar
spring-aop-4.0.7.RELEASE.jar
spring-beans-4.0.7.RELEASE.jar
spring-context-4.0.7.RELEASE.jar
spring-core-4.0.7.RELEASE.jar
spring-expression-4.0.7.RELEASE.jar
spring-integration-core-4.0.4.RELEASE.jar
spring-integration-http-4.0.4.RELEASE.jar
spring-integration-jms-4.0.4.RELEASE.jar
spring-jdbc-4.0.7.RELEASE.jar
spring-jms-4.0.7.RELEASE.jar
spring-messaging-4.0.7.RELEASE.jar
spring-oxm-4.0.7.RELEASE.jar
spring-retry-1.1.1.RELEASE.jar
spring-test-4.0.7.RELEASE.jar
spring-tx-4.0.7.RELEASE.jar
spring-web-4.0.7.RELEASE.jar
spring-webmvc-4.0.7.RELEASE.jar
spring-ws-core-2.2.0.RELEASE.jar
spring-xml-2.2.0.RELEASE.jar
stax-api-1.0-2.jar
stax-ex-1.7.4.jar
testng-6.8.jar
wsdl4j-1.6.3.jar
xalan-2.7.2.jar
xercesImpl-2.11.0.jar
xml-apis-1.4.01.jar

**Comment by christophd** [comment]
This is an issue with the Citrus ANT tutorial, we have to update this tutorial. Thanks for pointing to this issue. The basic idea would be to use the testng or junit ANT tasks instead.

**Comment by christophd** [comment]
I updated the ANT tutorial on the homepage http://www.citrusframework.org/tutorials-ant.html Please have a look and tell me if this is working for you
