### ISSUE TITLE
Combine two variables into one causes a test failure

### ISSUE THREAD

**Issue by aaschmid** [christophd/citrus#71]
If one executes the following test

```java
	@Test
	@CitrusTest
	public void test() throws SQLException {
		variable("ONE", "1");
		variable("TWO", "2");

		variable("TWELFE", "${ONE}${TWO}");
	}
```

he/she would get 

```
com.consol.citrus.exceptions.CitrusRuntimeException: Unknown variable 'ONE}${TWO'
	at com.consol.citrus.context.TestContext.getVariableObject(TestContext.java:122)
	at com.consol.citrus.context.TestContext.getVariable(TestContext.java:107)
	at com.consol.citrus.context.TestContext.resolveDynamicValue(TestContext.java:261)
	at com.consol.citrus.dsl.runner.DefaultTestRunner.variable(DefaultTestRunner.java:151)
	at com.consol.citrus.dsl.junit.JUnit4CitrusTestRunner.variable(JUnit4CitrusTestRunner.java:120)
	at com.****.test.integration.ws.testcase.***.test(***.java:649)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:203)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:188)
	at com.consol.citrus.dsl.junit.JUnit4CitrusTestRunner.run(JUnit4CitrusTestRunner.java:69)
	at com.consol.citrus.junit.CitrusJUnit4Runner$InvokeRunMethod.evaluate(CitrusJUnit4Runner.java:180)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by christophd** [comment]
You should use concat function here:

`variable("TWELFE", "citrus:concat(${ONE}, ${TWO})");`

**Comment by aaschmid** [comment]
Ah ok, but this is much more verbose and not very intuitive, isn't it?
