### ISSUE TITLE
escapeXml() won't work with `,` in sub-XML

### ISSUE THREAD

**Issue by toschneck** [christophd/citrus#94]
If the function `escapeXML` will be used with a content which contains an comma`,` the Function will get internal 2 Arguments if i set an Breakpoint and throw the Error `Invalid function parameter usage! Missing parameter!`

__Breackpoint `EscapeXmlFunction.java`__
```
 if (CollectionUtils.isEmpty(parameterList) || parameterList.size() != 1) {
            throw new InvalidFunctionUsageException("Invalid function parameter usage! Missing parameter!");
        }
        
        return StringEscapeUtils.escapeXml(parameterList.get(0));
```

__request.xml__
```
 <VAL_IN>citrus:escapeXml('<VAL_IN >
                    <test>with , an error occurs</test>
                  ')
 </VAL_IN>
```

__error__
```
com.consol.citrus.exceptions.InvalidFunctionUsageException: Invalid function parameter usage! Missing parameter!
	at com.consol.citrus.functions.core.EscapeXmlFunction.execute(EscapeXmlFunction.java:39)
	at com.consol.citrus.functions.FunctionUtils.resolveFunction(FunctionUtils.java:143)
	at com.consol.citrus.functions.FunctionUtils.replaceFunctionsInString(FunctionUtils.java:96)
	at com.consol.citrus.context.TestContext.replaceDynamicContentInString(TestContext.java:255)
	at com.consol.citrus.context.TestContext.replaceDynamicContentInString(TestContext.java:241)
	at com.consol.citrus.validation.builder.StaticMessageContentBuilder.buildMessagePayload(StaticMessageContentBuilder.java:70)
	at com.consol.citrus.validation.builder.StaticMessageContentBuilder.buildMessageContent(StaticMessageContentBuilder.java:52)
	at com.consol.citrus.actions.ReceiveMessageAction.createControlMessage(ReceiveMessageAction.java:219)
	at com.consol.citrus.actions.ReceiveMessageAction.validateMessage(ReceiveMessageAction.java:194)
	at com.consol.citrus.actions.ReceiveMessageAction.doExecute(ReceiveMessageAction.java:133)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.container.Sequence.doExecute(Sequence.java:47)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:42)
	at com.consol.citrus.container.Parallel$ActionRunner.run(Parallel.java:107)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by codemental** [comment]
This issue still appears when there are more comma "," characters. Like in this example:

```xml
@matchesXml('citrus:escapeXml('
                <PARENT_ELEMENT>
                    <TEST_FIELD1>CRM</TEST_FIELD1>
                    <TEST_FIELD2>StatNo=9899, SeqNo=567</TEST_FIELD2>
                    <TEST_FIELD3>LinkStatNo=8988, LinkSeqNo=789</TEST_FIELD3>
                </PARENT_ELEMENT>
')')@
```
